//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanAccount()
        {
            this.LoanTranscations = new HashSet<LoanTranscation>();
        }
    
        public string LnAccountid { get; set; }
        public string CustId { get; set; }
        public Nullable<int> lnAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<double> ROI { get; set; }
        public Nullable<double> EMI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTranscation> LoanTranscations { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
