//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcation
    {
        public int TranscationId { get; set; }
        public string Accountid { get; set; }
        public Nullable<System.DateTime> TranscationDate { get; set; }
        public string TranscationType { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual SavingsAccount SavingsAccount { get; set; }
    }
}
